import "primeicons/primeicons.css";
import "primereact/resources/primereact.min.css";
import "./globals.css";
import "primereact/resources/themes/lara-light-blue/theme.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { dir } from "i18next";

import CustomPrimeReactProvider from "~/components/providers/CustomPrimeReactProvider";
import { languages } from "~/i18n/settings";
import TheMainFooter from "~/components/layouts/TheMainFooter";
import { LanguageKey } from "~/interfaces/i18n.interface";
import TheMainHeader from "~/components/layouts/TheMainHeader";

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { lng },
}: Readonly<{
  children: React.ReactNode;
  params: {
    lng: LanguageKey;
  };
}>) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={inter.className}>
        <CustomPrimeReactProvider>
          <TheMainHeader />
          <main className="container mx-auto py-4">{children}</main>
          <TheMainFooter lng={lng} />
        </CustomPrimeReactProvider>
      </body>
    </html>
  );
}
